name: "Run Tests"
description: "Runs Anchor tests"
inputs:
  program:
    description: "Program to test"
    required: true
  solana_version:
    description: "Solana version used for cache"
    required: true
    default: ""
  anchor_version:
    description: "Anchor version used for cache"
    required: true
    default: ""
  features:
    description: "Features that will be passed into the test"
    required: false
  package_manager:
    description: "Package manager to use for installing JS dependencies"
    required: false
    default: "yarn"

runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ./node_modules/
        key: node-modules-${{ runner.os }}-build-v0.1-${{ inputs.anchor_version }}-${{ inputs.solana_version }}

    - name: Install pnpm
      if: inputs.package_manager == 'pnpm'
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6

    - name: Install Node.js dependencies
      shell: bash
      run: ${{ inputs.package_manager }} install

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          test-ledger/
        shared-key: "anchor-test-${{ inputs.anchor_version }}-${{ inputs.solana_version }}"

    - name: Install Surfpool (anchor >= 1.0.0)
      if: startsWith(inputs.anchor_version, '1.')
      shell: bash
      run: |
        curl -sL https://run.surfpool.run/ | bash

    - name: Run Anchor Tests
      shell: bash
      env:
        CARGO_INCREMENTAL: 1
        CARGO_NET_RETRY: 10
        RUST_BACKTRACE: 1
      run: |
        echo "Running tests for program: ${{ inputs.program }}"
                FEATURES="${{ inputs.features }}"
        if [ ! -z "$FEATURES" ]; then
          FEATURES="--features $FEATURES"
        fi

        anchor test -- $FEATURES

    - name: Check Test Results
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "Tests failed! Check the logs above for details."
        exit 1
